#!/bin/bash

set -x
pwd

## update and install zsh, oh-my-zsh and 
apt-get update
apt-get -o DPkg::Options::="--force-confnew" -y install zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

export ZSH="${HOME}/.oh-my-zsh"
export ZSH_CUSTOM=${ZSH}/custom
## order of events here matters - the statement above stomps any existing .zshrc bootstrapped into the container.
cp .zshrc ${HOME}/.zshrc

git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

git clone https://github.com/geometry-zsh/geometry.git "$ZSH_CUSTOM/themes/geometry" --depth=1
ln -s "$ZSH_CUSTOM/themes/geometry/geometry.zsh-theme" "$ZSH_CUSTOM/themes/geometry.zsh-theme"

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting



if [ -z "$(cat /root/.ssh/authorized_keys 2>/dev/null)" ]; then
  echo "Downloading SSH keys..."
  curl --silent --fail "https://github.com/jamisonhyatt.keys" > /${HOME}/.ssh/authorized_keys
fi
